import { FlashcardsConfig, FlashcardItem } from '../../types';
import { generateAIImageUrl } from '../../services/aiImageService';

export function getDefaultFlashcardsConfig(): FlashcardsConfig {
    return {
        title: 'Bộ Thẻ Học Từ Vựng AI - Visual Smart Flashcards',
        paperSize: 'a4',
        showAnswerKey: false,
        fontSize: 14,
        font: 'Inter',
        studentInfo: {
            showStudentInfo: false,
            showName: false,
            showClass: false,
            showDate: false,
            showScore: false,
        },
        borderStyle: 'none',
        zoom: 0.55,
        cardLayout: 'fold', // 'fold' or 'grid'
        cardsPerPage: 6,
        showCutLines: true,
        showImages: true,
        showIpa: true,
        showExamples: true,
        aiStyle: '3d_pixar',
        items: [
            {
                id: '1',
                frontText: 'Apple',
                frontSub: 'noun • /ˈæpl/',
                iconOrEmoji: '🍎',
                imageUrl: generateAIImageUrl('apple', '3d_pixar'),
                backText: 'Quả Táo',
                backSub: 'An apple a day keeps the doctor away.',
                partOfSpeech: 'noun',
                ipa: '/ˈæpl/',
                exampleEn: 'An apple a day keeps the doctor away.',
                exampleVi: 'Mỗi ngày một quả táo giúp bạn luôn khỏe mạnh.',
            },
            {
                id: '2',
                frontText: 'Cat',
                frontSub: 'noun • /kæt/',
                iconOrEmoji: '🐱',
                imageUrl: generateAIImageUrl('cat', '3d_pixar'),
                backText: 'Con Mèo',
                backSub: 'The cute cat is sleeping on the sofa.',
                partOfSpeech: 'noun',
                ipa: '/kæt/',
                exampleEn: 'The cute cat is sleeping on the sofa.',
                exampleVi: 'Chú mèo dễ thương đang ngủ trên ghế sofa.',
            },
            {
                id: '3',
                frontText: 'Rocket',
                frontSub: 'noun • /ˈrɒkɪt/',
                iconOrEmoji: '🚀',
                imageUrl: generateAIImageUrl('rocket', '3d_pixar'),
                backText: 'Tên Lửa',
                backSub: 'The rocket flies high into outer space.',
                partOfSpeech: 'noun',
                ipa: '/ˈrɒkɪt/',
                exampleEn: 'The rocket flies high into outer space.',
                exampleVi: 'Tên lửa bay vút lên không gian vũ trụ.',
            },
            {
                id: '4',
                frontText: 'Elephant',
                frontSub: 'noun • /ˈelɪfənt/',
                iconOrEmoji: '🐘',
                imageUrl: generateAIImageUrl('elephant', '3d_pixar'),
                backText: 'Con Voi',
                backSub: 'Elephants are the largest land animals.',
                partOfSpeech: 'noun',
                ipa: '/ˈelɪfənt/',
                exampleEn: 'Elephants are the largest land animals.',
                exampleVi: 'Voi là loài động vật trên cạn lớn nhất.',
            },
            {
                id: '5',
                frontText: 'Sun',
                frontSub: 'noun • /sʌn/',
                iconOrEmoji: '☀️',
                imageUrl: generateAIImageUrl('sun', '3d_pixar'),
                backText: 'Mặt Trời',
                backSub: 'The bright sun shines in the morning.',
                partOfSpeech: 'noun',
                ipa: '/sʌn/',
                exampleEn: 'The bright sun shines in the morning.',
                exampleVi: 'Mặt trời rực rỡ tỏa sáng vào buổi sáng.',
            },
            {
                id: '6',
                frontText: 'Rainbow',
                frontSub: 'noun • /ˈreɪnbəʊ/',
                iconOrEmoji: '🌈',
                imageUrl: generateAIImageUrl('rainbow', '3d_pixar'),
                backText: 'Cầu Vồng',
                backSub: 'A beautiful colorful rainbow after rain.',
                partOfSpeech: 'noun',
                ipa: '/ˈreɪnbəʊ/',
                exampleEn: 'A beautiful colorful rainbow after rain.',
                exampleVi: 'Một chiếc cầu vồng tuyệt đẹp sau cơn mưa.',
            },
        ],
    };
}
